//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// База клиента.
    /// </summary>
    // *** Start programmer edit section *** (БазаКлиента CustomAttributes)

    // *** End programmer edit section *** (БазаКлиента CustomAttributes)
    [AutoAltered()]
    [Caption("База клиента")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БазаКлиентаE", new string[] {
            "IDКлиента as \'I d клиента\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'",
            "НомерКарты as \'Номер карты\'"})]
    [View("БазаКлиентаL", new string[] {
            "IDКлиента as \'I d клиента\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'",
            "НомерКарты as \'Номер карты\'"})]
    public class БазаКлиента : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDКлиента;
        
        private string fЛогин;
        
        private string fПароль;
        
        private int fНомерКарты;
        
        // *** Start programmer edit section *** (БазаКлиента CustomMembers)

        // *** End programmer edit section *** (БазаКлиента CustomMembers)

        
        /// <summary>
        /// IDКлиента.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.IDКлиента CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.IDКлиента CustomAttributes)
        public virtual int IDКлиента
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.IDКлиента Get start)

                // *** End programmer edit section *** (БазаКлиента.IDКлиента Get start)
                int result = this.fIDКлиента;
                // *** Start programmer edit section *** (БазаКлиента.IDКлиента Get end)

                // *** End programmer edit section *** (БазаКлиента.IDКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.IDКлиента Set start)

                // *** End programmer edit section *** (БазаКлиента.IDКлиента Set start)
                this.fIDКлиента = value;
                // *** Start programmer edit section *** (БазаКлиента.IDКлиента Set end)

                // *** End programmer edit section *** (БазаКлиента.IDКлиента Set end)
            }
        }
        
        /// <summary>
        /// Логин.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.Логин CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.Логин CustomAttributes)
        [StrLen(255)]
        public virtual string Логин
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.Логин Get start)

                // *** End programmer edit section *** (БазаКлиента.Логин Get start)
                string result = this.fЛогин;
                // *** Start programmer edit section *** (БазаКлиента.Логин Get end)

                // *** End programmer edit section *** (БазаКлиента.Логин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.Логин Set start)

                // *** End programmer edit section *** (БазаКлиента.Логин Set start)
                this.fЛогин = value;
                // *** Start programmer edit section *** (БазаКлиента.Логин Set end)

                // *** End programmer edit section *** (БазаКлиента.Логин Set end)
            }
        }
        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.НомерКарты Get start)

                // *** End programmer edit section *** (БазаКлиента.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (БазаКлиента.НомерКарты Get end)

                // *** End programmer edit section *** (БазаКлиента.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.НомерКарты Set start)

                // *** End programmer edit section *** (БазаКлиента.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (БазаКлиента.НомерКарты Set end)

                // *** End programmer edit section *** (БазаКлиента.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Пароль.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.Пароль CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.Пароль CustomAttributes)
        [StrLen(255)]
        public virtual string Пароль
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.Пароль Get start)

                // *** End programmer edit section *** (БазаКлиента.Пароль Get start)
                string result = this.fПароль;
                // *** Start programmer edit section *** (БазаКлиента.Пароль Get end)

                // *** End programmer edit section *** (БазаКлиента.Пароль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.Пароль Set start)

                // *** End programmer edit section *** (БазаКлиента.Пароль Set start)
                this.fПароль = value;
                // *** Start programmer edit section *** (БазаКлиента.Пароль Set end)

                // *** End programmer edit section *** (БазаКлиента.Пароль Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БазаКлиентаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаКлиентаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаКлиентаE", typeof(IIS.Kursovaya4.БазаКлиента));
                }
            }
            
            /// <summary>
            /// "БазаКлиентаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаКлиентаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаКлиентаL", typeof(IIS.Kursovaya4.БазаКлиента));
                }
            }
        }
    }
}
