//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Покупка.
    /// </summary>
    // *** Start programmer edit section *** (Покупка CustomAttributes)

    // *** End programmer edit section *** (Покупка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупкаE", new string[] {
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'",
            "ЦенноваяСтела as \'Ценновая стела\'",
            "ЦенноваяСтела.Наименование as \'Наименование\'",
            "БазаКлиента as \'База клиента\'",
            "БазаКлиента.Логин as \'Логин\'"}, Hidden=new string[] {
            "ЦенноваяСтела.Наименование",
            "БазаКлиента.Логин"})]
    [AssociatedDetailViewAttribute("ПокупкаE", "Резервуар", "РезервуарE", true, "", "Резервуар", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПокупкаE", "ЦенноваяСтела", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПокупкаE", "БазаКлиента", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Логин")]
    [View("ПокупкаL", new string[] {
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'",
            "ЦенноваяСтела.Наименование as \'Наименование\'",
            "БазаКлиента.Логин as \'Логин\'"})]
    public class Покупка : ICSSoft.STORMNET.DataObject
    {
        
        private double fКоличество;
        
        private double fСумма;
        
        private IIS.Kursovaya4.ЦенноваяСтела fЦенноваяСтела;
        
        private IIS.Kursovaya4.БазаКлиента fБазаКлиента;
        
        private IIS.Kursovaya4.DetailArrayOfРезервуар fРезервуар;
        
        // *** Start programmer edit section *** (Покупка CustomMembers)

        // *** End programmer edit section *** (Покупка CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Покупка.Количество CustomAttributes)

        // *** End programmer edit section *** (Покупка.Количество CustomAttributes)
        public virtual double Количество
        {
            get
            {
                // *** Start programmer edit section *** (Покупка.Количество Get start)

                // *** End programmer edit section *** (Покупка.Количество Get start)
                double result = this.fКоличество;
                // *** Start programmer edit section *** (Покупка.Количество Get end)

                // *** End programmer edit section *** (Покупка.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупка.Количество Set start)

                // *** End programmer edit section *** (Покупка.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Покупка.Количество Set end)

                // *** End programmer edit section *** (Покупка.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Покупка.Сумма CustomAttributes)

        // *** End programmer edit section *** (Покупка.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Покупка.Сумма Get start)

                // *** End programmer edit section *** (Покупка.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Покупка.Сумма Get end)

                // *** End programmer edit section *** (Покупка.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупка.Сумма Set start)

                // *** End programmer edit section *** (Покупка.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Покупка.Сумма Set end)

                // *** End programmer edit section *** (Покупка.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Покупка.
        /// </summary>
        // *** Start programmer edit section *** (Покупка.БазаКлиента CustomAttributes)

        // *** End programmer edit section *** (Покупка.БазаКлиента CustomAttributes)
        [PropertyStorage(new string[] {
                "БазаКлиента"})]
        [NotNull()]
        public virtual IIS.Kursovaya4.БазаКлиента БазаКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Покупка.БазаКлиента Get start)

                // *** End programmer edit section *** (Покупка.БазаКлиента Get start)
                IIS.Kursovaya4.БазаКлиента result = this.fБазаКлиента;
                // *** Start programmer edit section *** (Покупка.БазаКлиента Get end)

                // *** End programmer edit section *** (Покупка.БазаКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупка.БазаКлиента Set start)

                // *** End programmer edit section *** (Покупка.БазаКлиента Set start)
                this.fБазаКлиента = value;
                // *** Start programmer edit section *** (Покупка.БазаКлиента Set end)

                // *** End programmer edit section *** (Покупка.БазаКлиента Set end)
            }
        }
        
        /// <summary>
        /// Покупка.
        /// </summary>
        // *** Start programmer edit section *** (Покупка.ЦенноваяСтела CustomAttributes)

        // *** End programmer edit section *** (Покупка.ЦенноваяСтела CustomAttributes)
        [PropertyStorage(new string[] {
                "ЦенноваяСтела"})]
        [NotNull()]
        public virtual IIS.Kursovaya4.ЦенноваяСтела ЦенноваяСтела
        {
            get
            {
                // *** Start programmer edit section *** (Покупка.ЦенноваяСтела Get start)

                // *** End programmer edit section *** (Покупка.ЦенноваяСтела Get start)
                IIS.Kursovaya4.ЦенноваяСтела result = this.fЦенноваяСтела;
                // *** Start programmer edit section *** (Покупка.ЦенноваяСтела Get end)

                // *** End programmer edit section *** (Покупка.ЦенноваяСтела Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупка.ЦенноваяСтела Set start)

                // *** End programmer edit section *** (Покупка.ЦенноваяСтела Set start)
                this.fЦенноваяСтела = value;
                // *** Start programmer edit section *** (Покупка.ЦенноваяСтела Set end)

                // *** End programmer edit section *** (Покупка.ЦенноваяСтела Set end)
            }
        }
        
        /// <summary>
        /// Покупка.
        /// </summary>
        // *** Start programmer edit section *** (Покупка.Резервуар CustomAttributes)

        // *** End programmer edit section *** (Покупка.Резервуар CustomAttributes)
        public virtual IIS.Kursovaya4.DetailArrayOfРезервуар Резервуар
        {
            get
            {
                // *** Start programmer edit section *** (Покупка.Резервуар Get start)

                // *** End programmer edit section *** (Покупка.Резервуар Get start)
                if ((this.fРезервуар == null))
                {
                    this.fРезервуар = new IIS.Kursovaya4.DetailArrayOfРезервуар(this);
                }
                IIS.Kursovaya4.DetailArrayOfРезервуар result = this.fРезервуар;
                // *** Start programmer edit section *** (Покупка.Резервуар Get end)

                // *** End programmer edit section *** (Покупка.Резервуар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Покупка.Резервуар Set start)

                // *** End programmer edit section *** (Покупка.Резервуар Set start)
                this.fРезервуар = value;
                // *** Start programmer edit section *** (Покупка.Резервуар Set end)

                // *** End programmer edit section *** (Покупка.Резервуар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупкаE", typeof(IIS.Kursovaya4.Покупка));
                }
            }
            
            /// <summary>
            /// "ПокупкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупкаL", typeof(IIS.Kursovaya4.Покупка));
                }
            }
        }
    }
}
