//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Резервуар.
    /// </summary>
    // *** Start programmer edit section *** (Резервуар CustomAttributes)

    // *** End programmer edit section *** (Резервуар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РезервуарE", new string[] {
            "КолвоТоп as \'Колво топ\'",
            "Состояние as \'Состояние\'",
            "IdР as \'Id Р\'"})]
    public class Резервуар : ICSSoft.STORMNET.DataObject
    {
        
        private double fКолвоТоп;
        
        private string fСостояние;
        
        private int fIdР;
        
        private IIS.Kursovaya4.Покупка fПокупка;
        
        // *** Start programmer edit section *** (Резервуар CustomMembers)

        // *** End programmer edit section *** (Резервуар CustomMembers)

        
        /// <summary>
        /// IdР.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.IdР CustomAttributes)

        // *** End programmer edit section *** (Резервуар.IdР CustomAttributes)
        public virtual int IdР
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.IdР Get start)

                // *** End programmer edit section *** (Резервуар.IdР Get start)
                int result = this.fIdР;
                // *** Start programmer edit section *** (Резервуар.IdР Get end)

                // *** End programmer edit section *** (Резервуар.IdР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.IdР Set start)

                // *** End programmer edit section *** (Резервуар.IdР Set start)
                this.fIdР = value;
                // *** Start programmer edit section *** (Резервуар.IdР Set end)

                // *** End programmer edit section *** (Резервуар.IdР Set end)
            }
        }
        
        /// <summary>
        /// КолвоТоп.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.КолвоТоп CustomAttributes)

        // *** End programmer edit section *** (Резервуар.КолвоТоп CustomAttributes)
        public virtual double КолвоТоп
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Get start)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Get start)
                double result = this.fКолвоТоп;
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Get end)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Set start)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Set start)
                this.fКолвоТоп = value;
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Set end)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Состояние CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Состояние CustomAttributes)
        [StrLen(255)]
        public virtual string Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Состояние Get start)

                // *** End programmer edit section *** (Резервуар.Состояние Get start)
                string result = this.fСостояние;
                // *** Start programmer edit section *** (Резервуар.Состояние Get end)

                // *** End programmer edit section *** (Резервуар.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Состояние Set start)

                // *** End programmer edit section *** (Резервуар.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Резервуар.Состояние Set end)

                // *** End programmer edit section *** (Резервуар.Состояние Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya4.Покупка.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Покупка CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Покупка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Покупка"})]
        public virtual IIS.Kursovaya4.Покупка Покупка
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Покупка Get start)

                // *** End programmer edit section *** (Резервуар.Покупка Get start)
                IIS.Kursovaya4.Покупка result = this.fПокупка;
                // *** Start programmer edit section *** (Резервуар.Покупка Get end)

                // *** End programmer edit section *** (Резервуар.Покупка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Покупка Set start)

                // *** End programmer edit section *** (Резервуар.Покупка Set start)
                this.fПокупка = value;
                // *** Start programmer edit section *** (Резервуар.Покупка Set end)

                // *** End programmer edit section *** (Резервуар.Покупка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РезервуарE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезервуарE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезервуарE", typeof(IIS.Kursovaya4.Резервуар));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Резервуар.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРезервуар CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРезервуар CustomAttributes)
    public class DetailArrayOfРезервуар : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya4.DetailArrayOfРезервуар members)

        // *** End programmer edit section *** (IIS.Kursovaya4.DetailArrayOfРезервуар members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Резервуар by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Резервуар.
        /// </summary>
        public DetailArrayOfРезервуар(IIS.Kursovaya4.Покупка fПокупка) : 
                base(typeof(Резервуар), ((ICSSoft.STORMNET.DataObject)(fПокупка)))
        {
        }
        
        public IIS.Kursovaya4.Резервуар this[int index]
        {
            get
            {
                return ((IIS.Kursovaya4.Резервуар)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya4.Резервуар dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
